[build]
  publish = "client/build"
  command = "cd client && npm install --legacy-peer-deps && CI=false npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  force = true
